# The path to the build directory
BUILD_DIR := build

# Default target executed when no arguments are given to make.
all: build_project

# Create the build directory if it doesn't exist
$(BUILD_DIR):
	mkdir -p $(BUILD_DIR)

# Target that runs qmake in the build directory, generating a Makefile there
$(BUILD_DIR)/Makefile: | $(BUILD_DIR)
	cd $(BUILD_DIR) && qmake ../src

# Target to build the project using the Makefile generated by qmake
build_project: $(BUILD_DIR)/Makefile
	$(MAKE) -C $(BUILD_DIR)

# Run the simulation executable
run: build_project
	./$(BUILD_DIR)/simulation

doxygen:
	doxygen Doxyfile
ifeq ($(OS),Windows_NT)
	start doc/html/index.html
else
	xdg-open doc/html/index.html
endif

pack:
	zip -r xkinin00-xslabi01 src/ doc/ examples/ Makefile Doxyfile README.txt ClassDiagram.pdf

# Clean up the build directory
clean:
	rm -rf $(BUILD_DIR) doc/

.PHONY: all build_project run clean

